/* Generated By:JavaCC: Do not edit this line. GameMonkeyParserTreeConstants.java Version 5.0 */
package org.gamemonkey.jcc.parser;

public interface GameMonkeyParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;


  public String[] jjtNodeName = {
    "CompilationUnit",
  };
}
/* JavaCC - OriginalChecksum=8f32b1e9f7e05f22b40bc63e907430b6 (do not edit this line) */
