/* Generated By:JavaCC: Do not edit this line. GameMonkeyLexerConstants.java */
package org.gamemonkey.jcc.lexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GameMonkeyLexerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int GLOBAL = 9;
  /** RegularExpression Id. */
  int LOCAL = 10;
  /** RegularExpression Id. */
  int MEMBER = 11;
  /** RegularExpression Id. */
  int FUNCTION = 12;
  /** RegularExpression Id. */
  int THIS = 13;
  /** RegularExpression Id. */
  int DOSTRING = 14;
  /** RegularExpression Id. */
  int TABLE = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int FOR = 18;
  /** RegularExpression Id. */
  int FOREACH = 19;
  /** RegularExpression Id. */
  int WHILE = 20;
  /** RegularExpression Id. */
  int DOWHILE = 21;
  /** RegularExpression Id. */
  int BREAK = 22;
  /** RegularExpression Id. */
  int CONTINUE = 23;
  /** RegularExpression Id. */
  int RETURN = 24;
  /** RegularExpression Id. */
  int TRUE = 25;
  /** RegularExpression Id. */
  int FALSE = 26;
  /** RegularExpression Id. */
  int NULL = 27;
  /** RegularExpression Id. */
  int PRINT = 28;
  /** RegularExpression Id. */
  int THREAD = 29;
  /** RegularExpression Id. */
  int YIELD = 30;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 31;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 32;
  /** RegularExpression Id. */
  int HEX_LITERAL = 33;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 34;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 35;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 36;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 37;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 38;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 39;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 40;
  /** RegularExpression Id. */
  int STRING_LITERAL = 41;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;
  /** RegularExpression Id. */
  int LETTER = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int OTHER = 45;
  /** RegularExpression Id. */
  int LPAREN = 46;
  /** RegularExpression Id. */
  int RPAREN = 47;
  /** RegularExpression Id. */
  int LBRACE = 48;
  /** RegularExpression Id. */
  int RBRACE = 49;
  /** RegularExpression Id. */
  int LBRACKET = 50;
  /** RegularExpression Id. */
  int RBRACKET = 51;
  /** RegularExpression Id. */
  int SEMICOLON = 52;
  /** RegularExpression Id. */
  int COMMA = 53;
  /** RegularExpression Id. */
  int DOT = 54;
  /** RegularExpression Id. */
  int AT = 55;
  /** RegularExpression Id. */
  int ASSIGN = 56;
  /** RegularExpression Id. */
  int LT = 57;
  /** RegularExpression Id. */
  int BANG = 58;
  /** RegularExpression Id. */
  int TILDE = 59;
  /** RegularExpression Id. */
  int HOOK = 60;
  /** RegularExpression Id. */
  int COLON = 61;
  /** RegularExpression Id. */
  int EQ = 62;
  /** RegularExpression Id. */
  int LE = 63;
  /** RegularExpression Id. */
  int GE = 64;
  /** RegularExpression Id. */
  int NE = 65;
  /** RegularExpression Id. */
  int SC_OR = 66;
  /** RegularExpression Id. */
  int SC_AND = 67;
  /** RegularExpression Id. */
  int INCR = 68;
  /** RegularExpression Id. */
  int DECR = 69;
  /** RegularExpression Id. */
  int PLUS = 70;
  /** RegularExpression Id. */
  int MINUS = 71;
  /** RegularExpression Id. */
  int STAR = 72;
  /** RegularExpression Id. */
  int SLASH = 73;
  /** RegularExpression Id. */
  int BIT_AND = 74;
  /** RegularExpression Id. */
  int BIT_OR = 75;
  /** RegularExpression Id. */
  int XOR = 76;
  /** RegularExpression Id. */
  int REM = 77;
  /** RegularExpression Id. */
  int LSHIFT = 78;
  /** RegularExpression Id. */
  int PLUSASSIGN = 79;
  /** RegularExpression Id. */
  int MINUSASSIGN = 80;
  /** RegularExpression Id. */
  int STARASSIGN = 81;
  /** RegularExpression Id. */
  int SLASHASSIGN = 82;
  /** RegularExpression Id. */
  int ANDASSIGN = 83;
  /** RegularExpression Id. */
  int ORASSIGN = 84;
  /** RegularExpression Id. */
  int XORASSIGN = 85;
  /** RegularExpression Id. */
  int REMASSIGN = 86;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 87;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 88;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 89;
  /** RegularExpression Id. */
  int ELLIPSIS = 90;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 91;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 92;
  /** RegularExpression Id. */
  int GT = 93;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "\"//\"",
    "<token of kind 3>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 8>",
    "\"global\"",
    "\"Local\"",
    "\"member\"",
    "\"function\"",
    "\"this\"",
    "\"dostring\"",
    "\"table\"",
    "\"if\"",
    "\"else\"",
    "\"for\"",
    "\"foreach\"",
    "\"while\"",
    "\"dowhile\"",
    "\"break\"",
    "\"continue\"",
    "\"return\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"print\"",
    "\"thread\"",
    "\"yield\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<OTHER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
