/* Generated By:JavaCC: Do not edit this line. GameMonkeyParserTreeConstants.java Version 5.0 */
package org.gamemonkey.jcc.parser;

public interface GameMonkeyParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTEXPRESSION = 1;
  public int JJTVARIABLE = 2;
  public int JJTCOMMAND = 3;
  public int JJTCOMMANDARGS = 4;
  public int JJTCOMMANDARG = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTFUNCTIONDEFINITION = 7;
  public int JJTBLOCK = 8;
  public int JJTSCOPELESSASSIGNMENT = 9;
  public int JJTDEFININGARGS = 10;
  public int JJTSCOPE = 11;
  public int JJTASSIGNOPERATOR = 12;
  public int JJTLITERAL = 13;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "Expression",
    "Variable",
    "Command",
    "CommandArgs",
    "CommandArg",
    "Assignment",
    "FunctionDefinition",
    "Block",
    "ScopelessAssignment",
    "DefiningArgs",
    "Scope",
    "AssignOperator",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=5aca07f2e9ace3a8b26d9fcd92d0db07 (do not edit this line) */
