/* Generated By:JavaCC: Do not edit this line. GameMonkeyParserTreeConstants.java Version 5.0 */
package org.gamemonkey.jcc.parser;

public interface GameMonkeyParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTEXPRESSION = 1;
  public int JJTVARIABLE = 2;
  public int JJTCOMMAND = 3;
  public int JJTASSIGNMENT = 4;
  public int JJTFUNCTIONDEFINITION = 5;
  public int JJTBLOCK = 6;
  public int JJTSCOPELESSASSIGNMENT = 7;
  public int JJTVALIDASSIGNMENTS = 8;
  public int JJTVALIDASSIGNMENT = 9;
  public int JJTDEFININGARGS = 10;
  public int JJTSCOPE = 11;
  public int JJTASSIGNOPERATOR = 12;
  public int JJTLITERAL = 13;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "Expression",
    "Variable",
    "Command",
    "Assignment",
    "FunctionDefinition",
    "Block",
    "ScopelessAssignment",
    "ValidAssignments",
    "ValidAssignment",
    "DefiningArgs",
    "Scope",
    "AssignOperator",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=12288a60c7921926efbed7850df0b0b1 (do not edit this line) */
