/* Generated By:JavaCC: Do not edit this line. GameMonkeyParserTreeConstants.java Version 5.0 */
package org.gamemonkey.jcc.parser;

public interface GameMonkeyParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTMODIFIERS = 1;
  public int JJTNAME = 2;
  public int JJTNAMELIST = 3;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "Modifiers",
    "Name",
    "NameList",
  };
}
/* JavaCC - OriginalChecksum=58d7e1dc4354e25b6a64d17633b43d35 (do not edit this line) */
